# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: win-agent-pool-1

steps:

- task: PythonScript@0
  inputs:
      pythonInterpreter: 'C:/Python/python.exe'
      scriptSource: inline
      script: |
          import requests
          print("Done")
