# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: win-agent-pool-1

steps:

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      CD C:
      mkdir tools;
      cd tools;
      mkdir Python;

      CD $Env:Temp;
      echo "Enabling Windows Installer Service";
      MSIEXEC /UNREG;
      MSIEXEC /REGSERVER;
      echo "Downloading Python";
      Invoke-WebRequest -Uri "https://chesterliudevstorage.z21.web.core.windows.net/python3.7.9.zip" -OutFile "python3.7.9.zip";
    
      echo "Installing Python"; 
      Expand-Archive python3.7.9.zip -DestinationPath C:\tools\Python\

- task: PythonScript@0
  inputs:
      pythonInterpreter: C:\Users\$e\AppData\Local\Programs\Python\Python37\Python.exe
      scriptSource: inline
      script: |
          import requests
          print("Done")
