# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: win-agent-pool-1

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      CD $Env:Temp;
      echo "Downloading Python";
      Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe" -OutFile "python-3.7.9-amd64.exe";
      echo "Installing Python";
      .\python-3.7.9-amd64.exe /quiet PrependPath=1 TargetDir="C:\Python" Include_test=0;
      Start-Sleep 120;

- task: PythonScript@0
  inputs:
      pythonInterpreter: 'C:/Python/python.exe'
      scriptSource: inline
      script: |
          import requests
          print("Done")
